<?xml version="1.0" ?>
<testsuite name="tests.util.test_keplerSTM.TestKeplerSTM-20240620165936" tests="6" time="0.023" failures="0" errors="1">
	<testcase classname="tests.util.test_keplerSTM.TestKeplerSTM" name="test_keplerSTM_indpropC" time="0.000"/>
	<testcase classname="tests.util.test_keplerSTM.TestKeplerSTM" name="test_keplerSTM_indproppy" time="0.005"/>
	<testcase classname="tests.util.test_keplerSTM.TestKeplerSTM" name="test_keplerSTM_propC" time="0.005"/>
	<testcase classname="tests.util.test_keplerSTM.TestKeplerSTM" name="test_keplerSTM_prop_vallado" time="0.005"/>
	<testcase classname="tests.util.test_keplerSTM.TestKeplerSTM" name="test_keplerSTM_proppy" time="0.007"/>
	<testcase classname="tests.util.test_keplerSTM.TestKeplerSTM" name="test_keplerSTM_init" time="0.001">
		<error type="AssertionError" message="True is not false"><![CDATA[Traceback (most recent call last):
  File "/Users/maxzweig/research/EXOSIMS/tests/util/test_keplerSTM.py", line 168, in test_keplerSTM_init
    self.assertFalse(ps3.havec)
AssertionError: True is not false
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
