<?xml version="1.0" ?>
<testsuite name="unittest.loader._FailedTest-20240620173819" tests="2" time="0.000" failures="0" errors="2">
	<testcase classname="unittest.loader._FailedTest" name="p" time="0.000">
		<error type="AttributeError" message="module 'tests.util.test_keplerSTM' has no attribute 'p'"><![CDATA[AttributeError: module 'tests.util.test_keplerSTM' has no attribute 'p'
]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="--no-binaries" time="0.000">
		<error type="ImportError" message="Failed to import test module: --no-binaries
Traceback (most recent call last):
  File &quot;/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named '--no-binaries'
"><![CDATA[ImportError: Failed to import test module: --no-binaries
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named '--no-binaries'

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
